# Generated by Django 3.2 on 2024-08-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified',
            new_name='modified_at',
        ),
    ]
