# Generated by Django 3.2 on 2024-08-04 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='카드 이름')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardSellRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='등록삭제 날짜')),
                ('selled_at', models.DateTimeField(blank=True, null=True, verbose_name='판매완료 날짜')),
                ('state', models.CharField(choices=[('selling', '판매중'), ('selled', '판매완료'), ('trading', '거래중')], default='selling', max_length=10, verbose_name='상태')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('fee', models.PositiveIntegerField(verbose_name='수수료')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='카드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='판매자')),
            ],
            options={
                'verbose_name_plural': '카드 판매 등록',
            },
        ),
        migrations.CreateModel(
            name='CardSellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('card_sell_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardsellregister', verbose_name='카드 판매 등록')),
            ],
            options={
                'verbose_name_plural': '카드 판매 이력',
            },
        ),
        migrations.CreateModel(
            name='CardBuyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('card_sell_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.cardsellregister', verbose_name='카드 판매 등록')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name_plural': '카드 구매 이력',
            },
        ),
    ]
