# Generated by Django 3.2 on 2024-08-04 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsellregister',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='cardbuyhistory',
            name='card_sell_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.cardsellregister', verbose_name='카드 판매 등록'),
        ),
        migrations.AlterField(
            model_name='cardsellhistory',
            name='card_sell_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.cardsellregister', verbose_name='카드 판매 등록'),
        ),
        migrations.AlterField(
            model_name='cardsellregister',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card', verbose_name='카드'),
        ),
        migrations.AlterField(
            model_name='cardsellregister',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='등록삭제 날짜'),
        ),
        migrations.AlterField(
            model_name='cardsellregister',
            name='selled_at',
            field=models.DateTimeField(null=True, verbose_name='판매완료 날짜'),
        ),
        migrations.CreateModel(
            name='CardPossesionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(verbose_name='판매 가능 수량')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.card', verbose_name='카드')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name_plural': '카드 소유 현황',
            },
        ),
    ]
